version: "2.3"
services:
  main-cpu: &default
    image: esrgan
    build:
      context: .
    volumes:
      - '.:/app/esrgan'
    working_dir: /app/esrgan
    entrypoint: python3 -u main.py
  main:
    <<: *default
#    runtime: nvidia
